name: core_storage
description: Drift database, secure storage, shared preferences.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../core_foundation
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28
  flutter_secure_storage: ^9.2.3
  shared_preferences: ^2.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.23.1
  mocktail: ^1.0.4
