name: core_realtime
description: WebSocket client for Hocuspocus real-time collaboration.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  core_foundation:
    path: ../core_foundation
  core_network:
    path: ../core_network
  domain_core:
    path: ../../domain/domain_core
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  meta: ^1.16.0
  riverpod_annotation: ^2.5.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.1
  very_good_analysis: ^6.0.0
