name: core_realtime
description: WebSocket client for Hocuspocus real-time collaboration.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../core_foundation
  core_network:
    path: ../core_network
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  mocktail: ^1.0.4
