name: domain_core
description: Entities (Freezed), use cases, and repository interfaces.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../../core/core_foundation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
