name: file_service
description: File upload, download, and caching.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../../core/core_foundation
  core_network:
    path: ../../core/core_network
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  mocktail: ^1.0.4
