name: core_foundation
description: Either, Failure, typedefs, extensions, and shared utilities.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  intl: ">=0.19.0"
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
